# Generated by Django 5.1.6 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=150),
            preserve_default=False,
        ),
    ]
